const Actions = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  CHANGE_ADDFORM_AVAIL: 'CHANGE_ADDFORM_AVAIL',
  CHANGE_ADDFORM_CATEGORY: 'CHANGE_ADDFORM_CATEGORY',
  UPDATE_INGREDIENT_AVAIL: 'UPDATE_INGREDIENT_AVAIL',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT'
};

export default Actions;