export const Action = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  LOAD_INCREDIENTS: 'LOAD_INCREDIENTS',
  CHANGE_ADDFORM_AVAIL: 'CHANGE_ADDFORM_AVAIL',
  CHANGE_ADDFORM_CATEGORY: 'CHANGE_ADDFORM_CATEGORY',
  TOGGLE_INGREDIENT_AVAIL: 'TOGGLE_INGREDIENT_AVAIL',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  ADD_CATEGORIES: 'ADD_CATEGORIES',
  TOGGLE_CATEGORY_COLLAPSE: 'TOGGLE_CATEGORY_COLLAPSE'
};