const Action = {
  INGREDIENT_ADD: 'INGREDIENT_ADD',
  INGREDIENTS_LOAD: 'INGREDIENTS_LOAD',
  INGRED_FORM_UPDATE: 'INGRED_FORM_UPDATE',
  INGRED_AVAIL_TOGGLE: 'INGRED_AVAIL_TOGGLE',
  INGREDIENT_DELETE: 'INGREDIENT_DELETE',

  LOADING_SHOW: 'LOADING_SHOW',
  LOADING_HIDE: 'LOADING_HIDE',

  CAT_OPEN_TOGGLE: 'CAT_OPEN_TOGGLE',
  CATS_UPDATE_ALL: 'CATS_UPDATE_ALL',
  CATS_LOAD: 'CATS_LOAD',

  INIT_DATA_FETCH: 'INIT_DATA_FETCH',

  INGREDIENT_DB_DEL: 'INGREDIENT_DB_DEL',
  INGREDIENT_DB_SAVE: 'INGREDIENT_DB_SAVE',
  INGREDIENT_DB_TOGGLE: 'INGREDIENT_DB_TOGGLE',

  RECIPE_UPDATE_REQ: 'RECIPE_UPDATE_REQ',
  RECIPE_UPDATE_REQ_ING: 'RECIPE_UPDATE_REQ_ING',

  RECIPES_LOAD: 'RECIPES_LOAD',
  RECIPE_ADD_NEW: 'RECIPE_ADD_NEW',
  RECIPE_DELETE: 'RECIPE_DELETE',
  RECIPE_UPDATE_NAME: 'RECIPE_UPDATE_NAME',
  RECIPE_REMOVE_ING_NAME: 'RECIPE_REMOVE_ING_NAME',
};

export default Action;