const Action = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  LOAD_INCREDIENTS: 'LOAD_INCREDIENTS',
  UPDATE_INGRED_FORM: 'UPDATE_INGRED_FORM',
  TOGGLE_INGREDIENT_AVAIL: 'TOGGLE_INGREDIENT_AVAIL',
  DELETE_INGREDIENT: 'DELETE_INGREDIENT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  TOGGLE_CATEGORY_COLLAPSE: 'TOGGLE_CATEGORY_COLLAPSE',
  UPDATE_ALL_CATEGORIES: 'UPDATE_ALL_CATEGORIES'
};

export default Action;