const Action = {
  INGREDIENT_ADD: 'INGREDIENT_ADD',
  INGREDIENTS_LOAD: 'INGREDIENTS_LOAD',
  INGRED_FORM_UPDATE: 'INGRED_FORM_UPDATE',
  INGRED_AVAIL_TOGGLE: 'INGRED_AVAIL_TOGGLE',
  INGREDIENT_DELETE: 'INGREDIENT_DELETE',

  LOADING_SHOW: 'LOADING_SHOW',
  LOADING_HIDE: 'LOADING_HIDE',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',

  CAT_OPEN_TOGGLE: 'CAT_OPEN_TOGGLE',
  CATS_UPDATE_ALL: 'CATS_UPDATE_ALL',

  INIT_DATA_FETCH: 'INIT_DATA_FETCH',

  INGREDIENT_DB_DEL: 'INGREDIENT_DB_DEL',
  INGREDIENT_DB_SAVE: 'INGREDIENT_DB_SAVE',
  INGREDIENT_DB_TOGGLE: 'INGREDIENT_DB_TOGGLE',
};

export default Action;